### ISSUE TITLE
Warning about no sodium installed while using sinytra connector on forge

### ISSUE THREAD

**Issue by AutismOverload** [m3t4f1v3/voxy#7]
Hello,
I really respect your work on this backport for 1.20.1. Unfortunately I keep getting warning when it said that sodium needs to be installed when running it on forge with sinytra connector. I saw your posts  where the fix is to try forcing it to work with lwjgl 3.3.2 but it does not work. Of course I compiled the source code of yours to jar file but nothing works. I also tried with your build mc_1201-java17-3.3.1 but also nothing. I do not know what to do :(

**Comment by m3t4f1v3** [comment]
use a fabric loader dependency override

**Comment by AutismOverload** [comment]
Ok but do I need to put this in some gradle file settings or properties or somewhere else. I suspect that you did a lot of this type of helping but I am not an expert when it comes  to intelij.

**Comment by m3t4f1v3** [comment]
its a config file

**Comment by AutismOverload** [comment]
Well I tried a config file and I put this but it  does not work

{
  "version": 1,
  "overrides": {
    "voxy": {
      "depends": {
        "sodium": "*"
      }
    }
  }
}

**Comment by m3t4f1v3** [comment]
its -depends not just depends

**Comment by AutismOverload** [comment]
Ok i fixed that, in build.gradle i did not changed anything, i pulled your version with 3.3.1 and also add  files for  lwjgl 3.3.2 and edit in version file to be ok with 3.3.2 but I got this 

NoClassDefFoundError:
me.jellysquid.mods.sodium.client.gl.shader.ShaderConstants

**Comment by m3t4f1v3** [comment]
just remove the sodium entry from fabric.mod.json

**Comment by AutismOverload** [comment]
I  removed entry  from that file and got this HARD_DEP_NO_CANDIDATE voxy {depends sodium}, also add 
-Dsodium.checks.issue2561=false .  I really do not know what  I am  doing  wrong. Sorry for  wasting your tim  btw.

**Comment by m3t4f1v3** [comment]
get rid of your fabric loader depedency override

**Comment by AutismOverload** [comment]
Well it worked but I cant get  into config through menu but the world have created.  So I gess my config are only through its mod file   ?

**Comment by m3t4f1v3** [comment]
you can configure it through sodium too

**Comment by AutismOverload** [comment]
Got it, although world  was created the chunks are not generating even if I used chunky. So I gues there is nothig more for me from this point. But  thank you for helping :)

**Comment by m3t4f1v3** [comment]
use chunky fabric

**Comment by AutismOverload** [comment]
I got it got. I have to  use import command  after using chunky in my world :)  It is working. Thank you and Merry Christmas !
