### PR TITLE
Voxy 0.2.12-alpha

### PR DESCRIPTION
**Pull request by Riflusso**
Latest commit from dev branch that released yesterday. And some 1.20.1 adaptation of it:

- Return of fog rendering
- Water game chunks to LOD chunks smooth transition
- Software Rasterization port from 0.2.12
- Some bugs fixes from original repo that was made from 0.2.7 to 0.2.12 and I’m not aware of them

and many other things Idk about but which have been implemented

So that is hard work that works
Modded MC with 3 chunks of render distance demonstration

Update: that's not latest commit from dev branch now :D 
but that's latest release version :ok_hand:

### CODE REVIEW

**Comment by m3t4f1v3** [comment]
can you check the cherry trees and lava rendering

**Comment by Riflusso** [comment]
> can you check the cherry trees and lava rendering

What actually wrong with cherry leaves? Lava rendering works fine too

**Comment by m3t4f1v3** [comment]
looks fine, if you bp'ed just straight up they'd be black because of some weird shader changes that i messed with on this bp

**Comment by benjy-benjy** [comment]
I'm trying to set this up on 1.20.1. A few questions; is this Fabric only or does it work through Sinytra Connector on Forge? What are the exact required and optional dependencies and their versions? I'm running into conflicts overall so I'm not sure what I'm doing wrong because I can't even get the game to boot.

**Comment by Riflusso** [comment]
> I'm trying to set this up on 1.20.1. A few questions; is this Fabric only or does it work through Sinytra Connector on Forge? What are the exact required and optional dependencies and their versions? I'm running into conflicts overall so I'm not sure what I'm doing wrong because I can't even get the game to boot.

It works well on Forge with Sinytra Connector and Embeddium. Idk about fabric maybe not because of conflicts with latest sodium changes. You need to change one mixin to work with fabric I think

**Comment by benjy-benjy** [comment]
> > I'm trying to set this up on 1.20.1. A few questions; is this Fabric only or does it work through Sinytra Connector on Forge? What are the exact required and optional dependencies and their versions? I'm running into conflicts overall so I'm not sure what I'm doing wrong because I can't even get the game to boot.
> 
> It works well on Forge with Sinytra Connector and Embeddium. Idk about fabric maybe not because of conflicts with latest sodium changes. You need to change one mixin to work with fabric I think

I keep getting NoClassDefFoundError: org/lwjgl/system/windows/Kernel32 on both Fabric and Forge+Connector. It seems like Voxy needs the full LWJGL 3.3.3 base jar at runtime but the game ships 3.3.1. How are you getting around this? Is there a specific launcher setup or are you building Voxy against 3.3.1 instead?

**Comment by Riflusso** [comment]
> > > I'm trying to set this up on 1.20.1. A few questions; is this Fabric only or does it work through Sinytra Connector on Forge? What are the exact required and optional dependencies and their versions? I'm running into conflicts overall so I'm not sure what I'm doing wrong because I can't even get the game to boot.
> > 
> > 
> > It works well on Forge with Sinytra Connector and Embeddium. Idk about fabric maybe not because of conflicts with latest sodium changes. You need to change one mixin to work with fabric I think
> 
> I keep getting NoClassDefFoundError: org/lwjgl/system/windows/Kernel32 on both Fabric and Forge+Connector. It seems like Voxy needs the full LWJGL 3.3.3 base jar at runtime but the game ships 3.3.1. How are you getting around this? Is there a specific launcher setup or are you building Voxy against 3.3.1 instead?

I've used Prism Launcher with build in LWJGL 3.3.1 to run it.
Edit: Maybe it was bad decision to use LWJGL 3.3.3 for maybe 3-4 classes and we need to roll it back to 3.3.1 as @m3t4f1v3 did. But I've tested it on Linux with Prism Launcher and as I said it worked

**Comment by m3t4f1v3** [comment]
oh i didnt see that you undid the 3.3.1 stuff

**Comment by Riflusso** [comment]
> oh i didnt see that you undid the 3.3.1 stuff

Yeah, there were so much things that I've thought this would be great decision because it worked for me...
